after-login-command = []
after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

#on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
#on-focus-changed = "move-mouse window-lazy-center"

[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[exec]                   # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true  # If you don't touch "exec" section,
[exec.env-vars]          # it will fallback to "default-config.toml"
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[mode.main.binding]
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-f = 'fullscreen'

alt-s = 'layout v_tiles' # 'layout stacking' in i3
alt-w = 'layout h_tiles' # 'layout tabbed' in i3

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-b = 'workspace B' # for Browser
alt-m = 'workspace M' # for Music
alt-n = 'workspace N' # for Notes
alt-p = 'workspace P' # for Photo Editing
alt-t = 'workspace T' # for Terminal
alt-v = 'workspace V' # for Video Editing

alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-shift-b = ['move-node-to-workspace B', 'workspace B']
alt-shift-m = ['move-node-to-workspace M', 'workspace M']
alt-shift-n = ['move-node-to-workspace N', 'workspace N']
alt-shift-p = ['move-node-to-workspace P', 'workspace P']
alt-shift-t = ['move-node-to-workspace T', 'workspace T']
alt-shift-v = ['move-node-to-workspace V', 'workspace V']

cmd-h = []

alt-r = 'mode resize'
alt-shift-semicolon = 'mode service'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'secondary'
6 = 'secondary'
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'
T = 'main'
B = 'secondary'


#[[on-window-detected]]
#if.app-id = 'com.google.Chrome'
#run = 'move-node-to-workspace B'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace T'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run= [
  "layout tiling",
  'move-node-to-workspace T'
]

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = 'move-node-to-workspace B'

[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.AppStore'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.calculator'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.AddressBook'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.Dictionary'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.DiskUtility'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.FaceTime'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.findmy'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.Home'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.keychainaccess'
run = 'layout floating'


[[on-window-detected]]
if.app-id = 'com.apple.Maps'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.PhotoBooth'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.podcasts'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.QuickTimePlayerX'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.reminders'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.shortcuts'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.stocks'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.TV'
run = 'layout floating'

# S - Social
[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = ['layout floating', 'move-node-to-workspace S']

[[on-window-detected]]
if.app-id = 'com.tdesktop.Telegram'
run = ['layout floating', 'move-node-to-workspace S']

[[on-window-detected]]
if.app-id = 'jp.naver.line.mac'
run = ['layout floating', 'move-node-to-workspace S']

[[on-window-detected]]
if.app-id = 'org.whispersystems.signal-desktop'
run = ['layout floating', 'move-node-to-workspace S']

[[on-window-detected]]
if.app-id = 'com.tapbots.Ivory'
run = ['layout floating', 'move-node-to-workspace S']

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = ['layout floating', 'move-node-to-workspace S']

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = ['layout floating', 'move-node-to-workspace S']

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = ['layout floating', 'move-node-to-workspace S']


# -------------------------------------------------------
# Floating
# -------------------------------------------------------

[[on-window-detected]]
if.app-id = 'com.apple.Terminal'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.TextEdit'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.backup.launcher'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'org.videolan.vlc'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.VoiceMemos'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.VoiceOverUtility'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.weather'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.microsoft.Powerpoint'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.microsoft.Excel'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.amazon.clouddrive.mac'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'pl.maketheweb.cleanshotx'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.runningwithcrayons.Alfred-Preferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.utmapp.UTM'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.poly.lens.client.app'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.vmware.fusion'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.microsoft.rdc.macos'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'jp.co.sbisec.HYPERSBI2'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Photos'
run= [
  "layout floating",
  'move-node-to-workspace P'
]

[[on-window-detected]]
if.app-id = 'com.adobe.LightroomClassicCC7'
run= [
  "layout floating",
  'move-node-to-workspace P'
]
