scan_timeout = 10
add_newline = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[V](bold green)"

[aws]
disabled = true

[gcloud]
disabled = true

[terraform]
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
