# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$all$line_break$character"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[git_branch]
disabled = false

[aws]
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[time]
disabled = false
