# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[git_branch]
disabled = false

[aws]
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[aws.region_aliases]
ap-northeast-1 = 'tokyo'
ap-southeast-2 = 'au'
us-east-1 = 'va'
